# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins:
  - jekyll-paginate
  - jekyll-gist

# title: Oumar's website
# email: sekou.oumar.kaba@gmail.com
# description: >- # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://oumarkaba.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
# permalink: pretty
# paginate: 1

# markdown:         kramdown
# highlighter:      pygments

# github_username:  oumarkaba
# facebook_username: sekoumar.kaba
# linkedin_username: oumar-kaba

# # Build settings
# # theme: minima
# plugins:
#   - jekyll-feed
#   - jekyll-sitemap
#   - jekyll-seo-tag
#   - jekyll-gist


# exclude:
#   - .editorconfig
#   - .git
#   - .jekyll-cache
#   - Gemfile
#   - Gemfile.lock
#   - LICENSE.md
#   - README.md

# sass:
#   sass_dir: _sass
#   style: :compressed

